### ISSUE TITLE
Sectors are incorrectly divided

### ISSUE THREAD

**Issue by tercteberc** [andjash/AYPieChart#4]
Привет. Вылез баг неприятный. Сектора делятся неправильно. Сейчас если там есть иконка то сектор растягивается так, чтобы иконка влезла. Пофиксил пожалуйста так, чтобы сектора делились именно исходя из сумм а иконки вставлялись туда, куда они влезают. Ну при этом надо чтобы это работало при количестве секторов больше чем какая нить n. Какая n я думаю скажет тебе Кирилл. 
Вот задача, там в ней есть скрины. Там где 12 секторов видно что неправильно распределены расходы.
https://support.idamob.ru/issue/SDM-178

**Comment by andjash** [comment]
не доступа.

Сектора распределяются не точно в соответсвии со значениями. Они распределяются "примерно" пропорционально, для того, чтобы не было слишком маленьких секторов, в которые нельзя кликнуть. С иконками это никак не связано

**Comment by tercteberc** [comment]
Пофикшено? Обновил поды, но изменений нет

**Comment by andjash** [comment]
не будет пофикшено
